#############################################################################
# Makefile for building: car-ctrl
# Generated by qmake (2.01a) (Qt 4.8.5) on: Wed Oct 2 10:26:28 2013
# Project:  pwm-ctrl.pro
# Template: app
# Command: /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake -o Makefile pwm-ctrl.pro
#############################################################################

first: release
install: release-install
uninstall: release-uninstall
MAKEFILE      = Makefile
QMAKE         = /opt/trik-sdk/sysroots/i686-oesdk-linux/usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		release \
		debug

release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: pwm-ctrl.pro  /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/linux-g++/qmake.conf /opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/debug_and_release.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtGuiE.prl \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtNetworkE.prl \
		/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl
	$(QMAKE) -o Makefile pwm-ctrl.pro
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/linux.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/gcc-base-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/common/g++-unix.conf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/qconfig.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/modules/qt_webkit_version.pri:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_functions.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt_config.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/exclusive_builds.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_pre.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/release.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/debug_and_release.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/default_post.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/warn_on.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/shared.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/qt.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/unix/thread.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/moc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/resources.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/uic.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/yacc.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/lex.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/share/qtopia/mkspecs/features/include_source_dir.prf:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtGuiE.prl:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtNetworkE.prl:
/opt/trik-sdk/sysroots/armv5te-oe-linux-gnueabi/usr/lib/libQtCoreE.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile pwm-ctrl.pro

qmake_all: FORCE

make_default: release-make_default debug-make_default FORCE
make_first: release-make_first debug-make_first FORCE
all: release-all debug-all FORCE
clean: release-clean debug-clean FORCE
distclean: release-distclean debug-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
